#
# Copyright 2019 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += fsgal.o
obj-y += ddr.o
obj-y += ../fs_common/fs_common.o
obj-y += ../fs_common/fs_eth_common.o
obj-y += ../fs_common/fs_ls1028a_common.o
obj-y += ../fs_common/fs_fdt_common.o
