#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_EXYNOS_ACE_SHA)	+= ace_sha.o
obj-$(CONFIG_SECURITY_HAB) 	+= fsl/
obj-$(CONFIG_SECURITY_HAB)	+= rsa_mod_exp/
